var express = require('express');
var router = express.Router();
const userController = require('../controllers/userController');
router.post('/signin', userController.signin);
router.post('/signup', userController.signup);
router.post('/reservation', userController.getAppointment);
router.get('/statWempl', userController.getStatWEmpl);
router.get('/statResaPerDay', userController.getReservationPerDay);
router.get('/statResaPerMonth', userController.getReservationPerMonth);
router.get('/statCAPerDay', userController.reservationCAPerDay);
router.get('/statCAPerMonth', userController.reservationCAPerMonth);
router.post('/statBenefices', userController.beneficePerMonth);
router.post('/list-employee', userController.getResaByUser);
router.post('/horaire',userController.addOrUpdateHoraire);
router.post('/mon-horaire',userController.findHoraireUser);
module.exports = router;
